---
# This playbook contains common plays that will be run on all nodes.

- hosts: centosrhel
  become: yes
  tasks:
  - name: Install chrony
    yum: name=chrony state=installed
    tags: chrony

  - name: Allow ntp through firewall
    shell: firewall-cmd --add-service=ntp --permanent
   
  - name: Firewall reload
    shell: firewall-cmd --reload

  - name: Install libselinux-python
    yum: name=python3-libselinux state=installed
    tags: chrony
   
  - name: Install libsemanage-python
    yum: name=python3-libsemanage state=installed
    tags: chrony
              
  - name: Configure ntp file
    copy: src=ntp.conf.j2 dest=/etc/ntp.conf
    notify:
    - restart ntpd
    tags: ntp

  - name: Start the ntp service
    service: name=chronyd state=started enabled=yes
    tags: ntp

  handlers:
   - name: restart ntp
     service: name=ntpd state=restarted

