---
# This playbook deploys the whole application stack in this site.

# 1 Aplicar la configuracion en el rolo common a ambas distribuciones
- name: apply common configuration to all nodes
  hosts: all
  remote_user: ansible

  roles:
    - common

# 2 Aplicar configuracion web a distribuciones Ubuntu
- name: configure and deploy the webservers and application code
  hosts: webservers
  remote_user: ansible

  roles:
    - web

# 3 Aplicar configuracion de base de datos a distribuciones CentOS
- name: deploy MySQL and configure the databases
  hosts: dbservers
  remote_user: ansible

  roles:
    - db