---
# These tasks are responsible for copying the latest dev/production code from
# the version control system.

- name: Copy the code from repository
  ansible.builtin.git: 
    repo: "{{ repository }}"
    dest: /var/www/html/

- name: Configurar archivo index.php
  ansible.builtin.template:
    src: index.php.j2 
    dest: /var/www/html/index.php

