---
# These tasks install http and the php modules.

- hosts: webservers
  tasks:
  - name: Install httpd and other tools
    apt: 
      name: '{{ item }}'
      state: present
    loop:
        - apache2
        - php-mysql
        - git
        - php
        - libapache2-mod-security2
        - libapache2-mod-php
        

  - name: Allow all access to tcp port 80
    community.general.ufw:
      rule: allow
      port: '80'
      proto: tcp

  - name: Apache2 start
    ansible.builtin.systemd:
      name: apache2
      state: started
      enabled: yes

  - name: Make sure apache2 is running
    ansible.builtin.systemd:
      state: started
      name: apache2

 

  

  
  