---
# These tasks install http and the php modules.

- hosts: Ubuntu
  become: yes
  tasks:
  - name: Install httpd and php
    apt: 
      name: '{{ item }}'
      state: present
    loop:
        - apache2
        - php-mysql
        
  #- name: Copy your index page
   # template:
           #src: index.php.j2
           #dest: /var/www/index.html

  - name: insert iptables rule for httpd
     lineinfile:
       dest: /etc/sysconfig/iptables
       create: yes
       state: present
       regexp: "{{ httpd_port }}"
       insertafter: "^:OUTPUT "
       line: "-A INPUT -p tcp  --dport {{ httpd_port }} -j  ACCEPT"
       
  - name: http service state
    service: name=httpd state=started enabled=yes

  - name: Configure SELinux to allow httpd to connect to remote database
    seboolean:
       name: httpd_can_network_connect_db
       state: true
       persistent: yes
  