---
# This playbook will install MariaDB and create db user and give permissions.

- hosts: centosrhel 
  become: yes
  tasks:

      - name: Install maridab-server
        yum: name=mariadb-server state=latest
        with_items: 
                  -PyMySQL
                  -python3-pip

      - name: Make sure PyMySQL is present
        pip:
          name: pymysql
          state: present
        
      - name: Configure SELinux to start mysql on any port
        seboolean: name=mysql_connect_any state=true persistent=yes
      - name: Create Mysql configuration file
        template: src=my.cnf.j2 dest=/etc/my.cnf
        notify:
            - restart mariadb

      - name: Create MariaDB log file
        file: path=/var/log/mysqld.log state=touch owner=mysql group=mysql mode=0775

      - name: Create MariaDB PID directory
        file: path=/var/run/mysqld state=directory owner=mysql group=mysql mode=0775

      - name: Start MariaDB Service
        service: name=mariadb state=started enabled=yes

      - name: Start firewalld
        service: name=firewalld state=started enabled=yes

      - name: Insert firewalld rule
        firewalld: port=3306/tcp permanent=true state=enabled immediate=yes

      - name: Create Application Database
        mysql_db: name=obligatorio state=present

      - name: Create Application DB User
        mysql_user: name=ansible password=obligatorio priv=*.*:ALL host='%' state=present
      
- handlers:
      - name: restart mariadb
        service: name=mariadb state=restarted
