---
# This playbook will install MariaDB and create db user and give permissions.

- hosts: CentOS
  become: yes
  vars_files: 
   dbservers
  tasks:
  - name: Install MariaDB package
    yum: 
      name: "{{ item }}" 
      state: present
    loop:
      - mariadb-server
      - python3

  - name: Make sure pymysql is present
    pip:
      name: pymysql
      state: present
        
  - name: Configure SELinux to start mysql on any port
    seboolean: name=mysql_connect_any state=true persistent=yes
      
  - name: Create Mysql configuration file
    template: src=my.cnf.j2 dest=/etc/my.cnf
    
  - name: Create MariaDB log file
    file: path=/var/log/mysqld.log state=touch owner=mysql group=mysql mode=0775

  - name: Create MariaDB PID directory
    file: path=/var/run/mysqld state=directory owner=mysql group=mysql mode=0775

  - name: Start MariaDB Service
    service: name=mariadb state=started enabled=yes

  - name: Start firewalld
    service: name=firewalld state=started enabled=yes

  - name: Insert firewalld rule
    firewalld: port={{ mysql_port }}/tcp permanent=true state=enabled immediate=yes
    
  - name: Firewall reload
    shell: firewall-cmd --reload
    notify: restart mariadb
    
  - name: Create Application Database
    mysql_db: name={{ dbname }} state=present

  -  name: Create Application DB User
     mysql_user: name={{ dbuser }} password={{ upassword }} priv=*.*:ALL host='%' state=present
      
  handlers:
  - name: restart mariadb
    service: name=mariadb state=restarted
        